server:
  port: :8080

redis:
  host: localhost
  port: 6379
  cachetime: 3600

ninjas:
  definitionurl: https://api.api-ninjas.com/v1/dictionary
  defAPIKey: P9nis6bPQQRNLyrFK/yPaw==VJczzEp4moLZHGrk
  wordgeneratorurl: https://api.api-ninjas.com/v1/randomword