version: '3.8'

services:
  app:
    image: vocab:v1.4
    depends_on:
      - redis
    ports:
      - "8080:8080"
    networks:
      - my-network

  redis:
    image: redis:latest
    volumes:
      - data:/data
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - my-network

volumes:
  data:
    driver: local

networks:
  my-network:
    driver: bridge