version: '3.8'

services:
  app:
    image: ndawz/vocab:1730645520
    depends_on:
      - redis
    ports:
      - "8080:8080"
    networks:
      - my-network

  redis:
    image: redis:latest
    volumes:
      - data:/data
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - my-network
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - my-network
    depends_on:
      - app
      - redis

volumes:
  data:
    driver: local

networks:
  my-network:
    driver: bridge