apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  config.yaml: |
    server:
      port: :8080

    redis:
      host: redis
      port: 6379
      cachetime: 300

    ninjas:
      definitionurl: https://api.api-ninjas.com/v1/dictionary
      wordgeneratorurl: https://api.api-ninjas.com/v1/randomword
