apiVersion: v1
kind: Service
metadata:
  name: vocab-service
spec:
  selector:
    app: vocab-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
  type: NodePort
